import {digest as makeDigest} from './lib/rank.js';
const $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let state,digest;
const send=m=>chrome.runtime.sendMessage(m);
function img(x){if(x.imageUrl)return `<img class="image" loading="lazy" referrerpolicy="no-referrer" src="${esc(x.imageUrl)}">`;const i=(x.source||'TW').split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();return `<div class="image fallback">${esc(i)}</div>`}
function story(x){return `<details class="story" data-id="${esc(x.id)}"><summary><span class="plus">+</span><span class="storyTitle">${esc(x.title)}</span><span class="rowActions"><span class="meta">${esc(x.source)} · ${Math.round(x.score||0)}</span><button class="round ${x.newsmarked?'marked':''}" data-mark="${esc(x.id)}">${x.newsmarked?'★':'☆'}</button></span></summary><div class="body"><div class="copy"><p>${esc((x.summary||'No summary available.').slice(0,1000))}</p><div class="why"><b>Why Twin picked this</b><br>${esc(x.why||'Selected for relevance and significance.')}</div><div class="tags">${(x.topics||[]).slice(0,5).map(t=>`<span class="tag">${esc(t.replaceAll('_',' '))}</span>`).join('')}</div><div class="actions"><button class="markBtn ${x.newsmarked?'marked':''}" data-mark="${esc(x.id)}">${x.newsmarked?'★ Newsmarked':'☆ Newsmark'}</button><a class="read" href="${esc(x.url)}" target="_blank" data-open="${esc(x.id)}">Read original ↗</a></div></div>${img(x)}</div></details>`}
function findStory(id){return digest.ranked.find(x=>x.id===id)||state.newsmarks.find(x=>x.id===id)}
async function toggle(id){const s=findStory(id);if(!s)return;await send({type:'toggleNewsmark',story:s});await load()}
function wire(){document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();toggle(b.dataset.mark)});document.querySelectorAll('details.story').forEach(d=>d.ontoggle=()=>{if(d.open)send({type:'engage',storyId:d.dataset.id,action:'unfold'})});document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>send({type:'engage',storyId:a.dataset.open,action:'open_article'}));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));}
function go(id){const d=document.querySelector(`details.story[data-id="${CSS.escape(id)}"]`);if(!d)return;d.open=true;requestAnimationFrame(()=>{d.scrollIntoView({behavior:'smooth',block:'center'});d.classList.add('focus');setTimeout(()=>d.classList.remove('focus'),1400)});send({type:'engage',storyId:id,action:'today_open'})}
function bars(sel,rows){const max=Math.max(1,...rows.map(x=>x[1]));$(sel).innerHTML=rows.length?rows.map(([k,v])=>`<div class="barrow"><span>${esc(k.replaceAll('_',' '))}</span><div class="bar"><i style="width:${Math.round(v/max*100)}%"></i></div><b>${v}</b></div>`).join(''):'<div class="empty">Your graph builds as you read.</div>'}
function diet(){const day=new Date().toISOString().slice(0,10), es=state.engagements.filter(e=>(e.at||'').slice(0,10)===day);$('#dietTotal').textContent=es.length;const byT={},byS={};for(const e of es){const s=findStory(e.storyId);if(!s)continue;for(const t of s.topics||[])byT[t]=(byT[t]||0)+1;byS[s.source]=(byS[s.source]||0)+1}bars('#topicBars',Object.entries(byT).sort((a,b)=>b[1]-a[1]).slice(0,8));bars('#sourceBars',Object.entries(byS).sort((a,b)=>b[1]-a[1]).slice(0,8))}
async function load(){state=await send({type:'state'});digest=makeDigest(state.stories,state.profile,state.newsmarks);$('#name').textContent=(state.profile.name||'Selin')+'.';$('#markCount').textContent=state.newsmarks.length;$('#today').innerHTML=digest.top.map(x=>`<li><button class="todayTitle" data-go="${x.id}">${esc(x.title)}</button><div class="rowActions"><button class="round ${x.newsmarked?'marked':''}" data-mark="${x.id}">${x.newsmarked?'★':'☆'}</button><a class="round" target="_blank" href="${esc(x.url)}" data-open="${x.id}">↗</a><span class="score">${Math.round(x.score)}</span></div></li>`).join('')||'<div class="empty">Refresh Twin to build today’s briefing.</div>';$('#sections').innerHTML=digest.sections.map(s=>`<div class="category"><div class="catTitle"><h3>${esc(s.name)}</h3><small>${s.items.length} stories</small></div>${s.items.map(story).join('')}</div>`).join('');$('#deep').innerHTML=digest.deep.map(story).join('')||'<div class="empty">Deeper reads will appear here.</div>';$('#outside').innerHTML=digest.outside.map(x=>`<a href="${esc(x.url)}" target="_blank" data-open="${x.id}">${esc(x.title)}</a>`).join('')||'<p>Discovery stories appear after refresh.</p>';const tc={};digest.top.forEach(x=>(x.topics||[]).forEach(t=>tc[t]=(tc[t]||0)+1));$('#insideText').textContent=Object.entries(tc).sort((a,b)=>b[1]-a[1]).slice(0,4).map(x=>x[0].replaceAll('_',' ')).join(' · ')||'Your strongest themes today.';$('#marks').innerHTML=state.newsmarks.length?state.newsmarks.map(x=>story({...x,newsmarked:true})).join(''):'<div class="empty">No Newsmarks yet. Save a Twin story or right-click any webpage → ★ Newsmark this page.</div>';diet();wire();const when=state.lastRefresh?new Date(state.lastRefresh).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'never';$('#status').textContent=`Updated ${when}`}
$('#date').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#refresh').onclick=async()=>{const b=$('#refresh');b.disabled=true;b.textContent='Refreshing…';$('#status').textContent='Fetching feeds';const r=await send({type:'refresh'});b.disabled=false;b.textContent='Refresh';$('#status').textContent=r.error?'Refresh failed':`${r.fetched||0} fetched`;await load()};$('#newsmarksNav').onclick=()=>$('#newsmarks').scrollIntoView({behavior:'smooth'});load();
